### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by su314ka** [ericdesa/sentinelle#2]
Hello, 

When I run it, I receive the below error message.
There is something that I`m doing wrong?
Thanks!

D:\sentinelle-master> node index.js
module.js:515
    throw err;
    ^

Error: Cannot find module 'bigi'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\sentinelle-master\index.js:1:74)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
PS D:\sentinelle-master>

**Comment by ericdesa** [comment]
Hi,

This project use external librairies, have you install them ? 
`npm install`

I also push amissing file where the passphrases tested are logged (https://github.com/ericdesa/sentinelle/blob/master/output/tested.js)
